baseURL = "https://swiftlaggy.github.io/"
defaultContentLanguage = "en"
languageCode = "en"
title = "Jamie Gunner" # This appears in tab bar
timeZone = "Europe/London"
enableGitInfo = true
enableRobotsTXT = true

[module]
  [[module.imports]]
    path = "github.com/jackorcherton/hackit"


[menu]
  [[menu.main]]  
    identifer = "Home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]  
    identifer = "About"
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 3
 # [[menu.main]]
  #  identifier = "tags"
   # name = "Tags"
    #url = "/tags/"
    #weight = 3
  #[[menu.main]]
   # identifier = "categories"
    #name = "Categories"
    #url = "/categories/"
    #weight = 4

[params]
  version = "0.2.X"
  description = "Website for Jamie Gunner."
  keywords = ["Jamie", "Gunner", "Jamie Gunner", "Hacking", "Ethical", "Ethical Hacking", "CV", "Projects"]
  defaultTheme = "dark"
  gitRepo = "https://github.com/SwiftLaggy/SwiftLaggy.github.io"
  fingerprint = ""
  dateFormat = "2006-01-02"
   images = ["/images/sw.svg"] #favicon (I think)

  [params.app]
  # How site will appear on mobile
    title = "Jamie Gunner"
    noFavicon = true
    svgFavicon = "/images/sw.svg"
    # Android browser
    themeColor = "#ffffff"
    # Safari
    iconColor = "#5bbad5"
    # Windows tile color
    tileColor = "#da532c"

  [params.search]
    enable = true
    type = "lunr"
    contentLength = 4000
    placeholder = ""
    maxResultLength = 10
    snippetLength = 30
    highlightTag = "em"
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""

  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"
    [params.header.title]
      # URL of the LOGO
      #logo = "/images/sw.jpeg"
      name = "Jamie Gunner" # appears in header
      pre = ""
      post = ""
      typeit = false

  [params.footer]
    enable = true
    custom = ''
    hugo = false
    copyright = true
    author = true
    since = 2020
    icp = ""
    license = ''

  [params.section]
    paginate = 20
    dateFormat = "01-02"
    rss = 10

  [params.list]
    paginate = 20
    dateFormat = "01-02"
    rss = 10

  [params.home]
    rss = 10
    [params.home.profile]
      enable = true
      # For the avatar pic on the homepage
      avatarURL = "/images/sw.jpeg"
      avatarAlt = "Temporary avatar"
      title = "Jamie Gunner"
      subtitle = "A graduate of cyber security MSc also ethical hacking and cyber security BSc"
      disclaimer = "Welcome to my digital playground! Join me as I learn, problem-solve, and share my experiences tackling projects, mastering CTFs, and navigating TryHackMe and HackTheBox. Together, we'll decode the mysteries of technology!"
      typeit = true
      social = true #whether to show social icons on homepage

    [params.home.posts]
      enable = true
      paginate = 6
      defaultHiddenFromHomePage = false

  [params.social]
    GitHub = "SwiftLaggy"
    Linkedin = "jamie-gunner"
    Twitter = "SwiftLaggy"
    Reddit = "SwiftLaggy_"
    RSS = true

  [params.page]
    hiddenFromHomePage = false
    hiddenFromSearch = false
    twemoji = false
    lightgallery = false
    ruby = false
    fraction = false
    fontawesome = false
    linkToMarkdown = false
    rssFullText = false

    [params.page.toc]
      enable = true
      keepStatic = true
      auto = true

    [params.page.math]
      enable = false
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      copyTex = true
      mhchem = true
      
    [params.page.code]
      copy = true
      maxShownLines = 10

    [params.page.mapbox]
      accessToken = ""
      lightStyle = "mapbox://styles/mapbox/light-v9"
      darkStyle = "mapbox://styles/mapbox/dark-v9"
      navigation = true
      geolocate = true
      scale = true
      fullscreen = true

    [params.page.share]
      enable = false
      Twitter = true
      Facebook = true
      Linkedin = false
      Whatsapp = true
      Pinterest = false
      Tumblr = false
      HackerNews = false
      Reddit = false
      VK = false
      Buffer = false
      Xing = false
      Line = true
      Instapaper = false
      Pocket = false
      Digg = false
      Stumbleupon = false
      Flipboard = false
      Weibo = true
      Renren = false
      Myspace = true
      Blogger = true
      Baidu = false
      Odnoklassniki = false
      Evernote = true
      Skype = false
      Trello = false
      Mix = false

    [params.page.comment]
      enable = false
      [params.page.comment.utterances]
        enable = true
        # owner/repo
        repo = ""
        issueTerm = "pathname"
        label = "Comments"
        lightTheme = "github-light"
        darkTheme = "photon-dark"

    [params.page.seo]
      # image URL
      images = ["/images/sw.jpeg"]
      # Publisher info
      [params.page.seo.publisher]
        name = "Jamie Gunner"
        logoUrl = "/images/sw.jpeg"

  [params.typeit]
    speed = 50
    cursorSpeed = 1000
    cursorChar = "|"
    duration = -1

  [params.seo]
    # image URL
    image = ""
    # thumbnail URL
    thumbnailUrl = ""

  #  Analytics config
  [params.analytics]
    enable = false

  #  Cookie consent config
  [params.cookieconsent]
    enable = false

  #  Compatibility config
  [params.compatibility]
    # whether to use Polyfill.io to be compatible with older browsers
    polyfill = false
    # whether to use object-fit-images to be compatible with older browsers
    objectFit = false

# Markup related config in Hugo
[markup]
  # Syntax Highlighting
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false is a necessary configuration
    # (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true
  # Table Of Contents settings
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# Default post author (if not specified)
[author]
  name = ""
  email = ""
  link = ""

# Sitemap config
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks config
[Permalinks]
  # posts = ":year/:month/:filename"
  posts = "posts/:filename"

# Privacy config
[privacy]
  #  privacy of the Google Analytics (replaced by params.analytics.google)
  [privacy.googleAnalytics]
    # ...
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

# Options to make output .md files
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# Options to make output .md files
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# Options to make hugo output files
[outputs]
  # 
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
